version: '3'
services:
  db:
    image: mysql
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: cliques
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
